# Generated by Django 4.1.4 on 2023-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
